### ISSUE TITLE
Tag for MELPA Stable

### ISSUE THREAD

**Issue by camdez** [mattfidler/org-table-comment.el#1]
Hi Matthew,

I ran across your package today and thought it was pretty cool so I [added it to MELPA](https://github.com/milkypostman/melpa/pull/2624). It'd also love to get it on MELPA Stable, if possible.

[MELPA Stable](http://stable.melpa.org/) is the new younger sibling of MELPA for users who'd rather run only stable versions of packages (MELPA can be a bit rocky since every commit comprises a new release), and it would be super cool if org-table-comment could be installed via Stable.

Fortunately it's also really easy to support—all you have to do is define a tag in the `v...` format and you're done. I'd submit a PR if I could, but since tags are global to a project, that's not something possible via PR.

If you're cool with this idea, this should be all you have to do to make it happen:

``` sh
$ git tag v0.2.0 f98cce0cb8e793f9442a13d824df0d243dbe4e68
$ git push origin v0.2.0
```

(Of course, confirm that f98cce0cb8e793f9442a13d824df0d243dbe4e68 is the appropriate commit for the release, but it's the one where the version number was bumped to 0.2 so I suspect it is. You might also consider cutting a new 0.2.1 version to include your latest bugfixes.)

Thanks for your time and consideration!

**Comment by hadronzoo** [comment]
:+1:

**Comment by mattfidler** [comment]
Thats fine with me.

**Comment by mattfidler** [comment]
I think I have tagged it appropriately. Let me know if it shows up in MELPA stable.

**Comment by camdez** [comment]
Yessir! You can see it here: http://stable.melpa.org/#/org-table-comment

Thanks!
